name: 1k sky APK Build Action (new) z

on:
  workflow_dispatch:
    inputs:
      repository :
        description: 'git clone url'
        required: true
        default: "https://github.com/skylersaleh/SkyEmu.git"
      jdkVersion:
        description: "OpenJDK version to use: 8 / 11 / 17 etc."
        required: false
        default: "8"
      repo-commit:
        description: 'commit'
      
      
      

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

        
      - name: clone
        run: |
          git clone ${{ github.event.inputs.repository }}
          echo "projectName=$(basename -s .git ${{ github.event.inputs.repository }})" >> $GITHUB_ENV
          echo "dirName=$(echo ${{ github.event.inputs.repo-dir }} | sed -r 's/[/]+/ - /g')" >> $GITHUB_ENV
        
      - name: select commit
        if: ${{ github.event.inputs.repo-commit != '' }}
        run: |
          cd ${{ env.projectName }}
          git checkout ${{ github.event.inputs.repo-commit }}
          
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ github.event.inputs.jdkVersion }}

          
      - uses: sparkfabrik/android-build-action@v1.4.0
        with:
          project-path: tools/android_project
          output-path: SkyEmu.apk
          gradle-task: assemble
           

          
      - name: Upload the APK artifact with 1 day retention
        uses: actions/upload-artifact@v4
        with:
          path: ./*.apk
          retention-days: 1
          
      



